# application.yml
spring:
  datasource:
    url: jdbc:mysql://localvmdb.mysql_8:3306/sbp_study?characterEncoding=utf8
    username: sbp_user
    password: sbp_pass
  sql:
    init:
      mode: always
  # jpa:
  #   hibernate:
  #     naming:
  #       physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #   properties:
  #     hibernate:
  #       hbm2ddl:
  #         "[import_files_sql_extractor]": org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  #         "[charset_name]": UTF-8
  #       "[format_sql]": true
  #       "[show_sql]": true
  #     javax:
  #       persistence:
  #         schema-generation:
  #           database:
  #             action: drop-and-create
  #           drop-source: metadata
  #           create-source: metadata-then-script
  #           create-script-source: sql/hsqldb/init-data-insert.sql
  #   # open-in-view에 대해서 책 후반부에 논의하는 부분이 있다.
  #   open-in-view: false
