# application.yml
spring:
  datasource:
    url: jdbc:mysql://localvmdb.mysql_8:3306/sbp_study?characterEncoding=utf8&createDatabaseIfNotExist=true
    username: sbp_user
    password: sbp_pass
  jpa:
    # open-in-view에 대해서 책 후반부에 논의하는 부분이 있다.
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          "[import_files_sql_extractor]": org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
          "[charset_name]": UTF-8
        "[format_sql]": true
        "[show_sql]": true
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
            # DB의 모든 테이블을 삭제하는 MySQL 함수를 만들어둔 상태
            drop-source: script
            drop-script-source: sql/mysql/all-drop.sql
            create-source: metadata-then-script
            create-script-source: sql/mysql/data.sql
          sharedCache:
            mode: UNSPECIFIED
    database: mysql
  output:
    ansi:
      enabled: always
logging:
  level:
    web: INFO # logback-spring.xml을 따로 설정해도 이 설정도 같이 적용 됨.